### ISSUE TITLE
SDK - Parse Phone Number (Beta)

### ISSUE THREAD

**Issue by tehstun** [ringcentral/RingCentral.Net#5] opened 2019-06-17 10:54 UTC
### General
The SDK properties are incorrectly matched up with the SDK [documentation ](https://developers.ringcentral.com/api-reference/Phone-Numbers/parsePhoneNumber) that causes a casting error within the JSON parsing. The ```RingCentral.GetCountryInfoNumberParser[]``` just needs to be updated to match the documentation with ```RingCentral.GetCountryInfoNumberParser``` [Reference 1](https://github.com/ringcentral/RingCentral.Net/blob/be3248d8d8fb4b3e9eed9558e6f140613de744c9/RingCentral.Net/Definitions/PhoneNumberInfoNumberParser.cs#L13) and [Reference 2](https://github.com/ringcentral/RingCentral.Net/blob/be3248d8d8fb4b3e9eed9558e6f140613de744c9/RingCentral.Net/Definitions/ParsePhoneNumberResponse.cs#L14)

### Error
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'RingCentral.GetCountryInfoNumberParser[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'homeCountry.uri', line 4, position 11.

### Info
   * SDK Version: 1.2.0

### Code Snippet(s)

```csharp
var parseRequest = new ParsePhoneNumberRequest() { originalStrings = new string[] { phoneNumber } };
ParsePhoneNumberResponse phoneNumbers = await this.client.Restapi(this.version).NumberParser().Parse().Post(parseRequest);
```

**Comment by tylerlong** [comment] 2019-06-17 22:12
@tehstun  thanks for reporting this.

Actually all of the C# model classes are auto generated from swagger spec here: https://github.com/ringcentral/RingCentral.Net/blob/master/code-generator/rc-platform-adjusted.yml

And according to https://github.com/ringcentral/RingCentral.Net/blob/be3248d8d8fb4b3e9eed9558e6f140613de744c9/code-generator/rc-platform.yml#L21125
That field is indeed an array.

So the root cause is the swagger spec mismatches with server side behavior.

Please double check and confirm my conclusion. I will ask my teammate to fix the swagger first then I will re-generate the C# code here.

As a workaround, you can request the endpoint directly and parse the response yourself:

```C#
var r = await client.Post('/restapi/v1.0/numnber-parser/parse', parseRequest)
// extract body from `r` and parse it yourself.
```

**Comment by tylerlong** [comment] 2019-07-16 21:26
Issue fixed in latest version

**Closed by tylerlong** 2019-07-16 21:26 UTC

**Comment by tehstun** [comment] 2019-07-16 21:55
🎉
